### ISSUE TITLE
Testcase 20-pmc output checking

### ISSUE THREAD

**Issue by yalli-Boom** [mlichvar/linuxptp-testsuite#12]
Hi Miroslav,
Belows are the output of the testcase 20-pmc. Did this FAIL due to the extra "TIME_STATUS_NP" info?  
network with 3 nodes:
    non-default settings:
      jitter=0.0
      limit=51
      pmc_conf=SET SUBSCRIBE_EVENTS_NP duration 1 NOTIFY_PORT_STATE on NOTIFY_TIME_SYNC on NOTIFY_PARENT_DATA_SET on NOTIFY_CMLDS on
      pmc_node=3
      pmc_uds=2:1
      subnets=1 2 | 2 3
    starting node 1:                                    	OK
    starting node 2:                                    	OK
    starting node 3:                                    	OK
    running simulation:                                 	OK
    checking pmc output:                                	BAD
sending: SET SUBSCRIBE_EVENTS_NP
	123456.fffe.780102-0 seq 0 RESPONSE MANAGEMENT SUBSCRIBE_EVENTS_NP 
		duration               1
		NOTIFY_PORT_STATE      on
		NOTIFY_TIME_SYNC       on
		NOTIFY_PARENT_DATA_SET on
	123456.fffe.780102-0 seq 0 RESPONSE MANAGEMENT TIME_STATUS_NP 
		master_offset              0
		ingress_time               1262304050053466888
		cumulativeScaledRateOffset +0.000000000
		scaledLastGmPhaseChange    0
		gmTimeBaseIndicator        0
		lastGmPhaseChange          0x0000'0000000000000000.0000
		gmPresent                  true
		gmIdentity                 123456.fffe.780101
FAIL

**Comment by mlichvar** [comment]
It failed due to missing `NOTIFY_CMLDS on` in the pmc output. This is supported only in the latest linuxptp development code. It's not present in linuxptp-4.2.

**Comment by yalli-Boom** [comment]
Got it. Thanks!
