### ISSUE TITLE
Add test for automotive profile

### ISSUE THREAD

**Issue by jpm-canonical** [mlichvar/linuxptp-testsuite#13]
I'm trying to add a test to this suite that does a complete test using the automotive profile, as defined in [automotive-master.cfg](https://github.com/richardcochran/linuxptp/blob/master/configs/automotive-master.cfg) and [automotive-slave.cfg](https://github.com/richardcochran/linuxptp/blob/master/configs/automotive-slave.cfg). The attached `35-automotive` script is my attempt in creating a new test, using the preferences from these two config file. 

When enabling any one of these preferences, the test would fail:
```
# priority1			248		# priority1  attribute  of the local clock
# follow_up_info		1		# Include the 802.1AS data in the Follow_Up messages if enabled. The default is 0 (disabled).
# transportSpecific		0x1		# The transport specific field. Must be in the range 0 to 255. The default is 0.
# network_transport		L2		# The default is UDPv4.
# delay_mechanism		P2P		# The default is E2E.
# inhibit_announce		1		# Disables the timer for announce messages. Used by the Automotive profile as part of switching over to a static BMCA.
```

Is there a limitation with `clknetsim` that prevents these preferences from being changed away from their default values?

Any other recommendations for testing `ptp4l` in the simulator, using the automotive profile?

Test script:
[35-automotive.txt](https://github.com/mlichvar/linuxptp-testsuite/files/15457216/35-automotive.txt)

**Comment by mlichvar** [comment]
The L2  transport is not supported by clknetsim. Other than that I think it should work. The master and slave configuration variables need to match, e.g. if you change priority1 on master, it needs to be changed on slave too.

**Comment by jpm-canonical** [comment]
It looks like `extra_node_confs` do not work as I had thought. Moving the common configs into a new variable, and prefixing that to the `master_conf` and `slave_conf` works. 

`network_transport	L2` is omitted as it's not supported.
`delay_mechanism	P2P` is also omitted, as that breaks the test. Is this also not supported by `clknetsim`?

Test file:
[36-automotive.txt](https://github.com/mlichvar/linuxptp-testsuite/files/15500460/36-automotive.txt)

PR to follow.

**Comment by mlichvar** [comment]
P2P is supported. See the existing `03-p2pdm` test.
