### ISSUE TITLE
Under what Open Source License is this testsuite?

### ISSUE THREAD

**Issue by oracle2025** [mlichvar/linuxptp-testsuite#9]
Seeing that there is no mention of any Open Source License, I am wondering under what conditions this testsuite can be used, distributed and extended?

**Comment by mlichvar** [comment]
The intention is to follow the linuxptp licensing. The test.common file has the GPLv2+ header.

**Comment by oracle2025** [comment]
Thanks for the quick clarification @mlichvar ☺️👍
